language: node_js

# cache:
#  directories:
#  - node_modules

node_js:
  - 'stable'

sudo: false

before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
  - npm install -g typings
  - npm install -g codeclimate-test-reporter

script:
  - npm run build
  - npm run validate

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - node_modules/.bin/coveralls < coverage/lcov.info

before_deploy:
  - npm run build:dist && node ./script/package-dist.js

deploy:
  provider: npm
  email: 'larsvanbraam@gmail.com'
  api_key:
    secure: 'KiY/8L7O51BgFd+W5FCV57wCNKSmJGSwOOkEdSGYS+t66UtpB6Eido6vQF1OdXcEX4TETFtuINL150onEF0z3QGaVx0X0O5pPdxU3z64qTbwiAmHjbBc3MMXkWdN1zrm26x10E+fgLFjt44pEC0v49pihcd+mYSrJgZfc9wr1ITifxxpwwiv5wusJgiIJDGqPhp8QE8k6hRXITeufynuw1wAFROaasLxajHxKn6neJbpw4m0SSNxjVPwvDOuO/wHw437b57GFoZhupn7cjaS2k3y9F4drIC/aCJ/7pol26ybkXeyXKYbx54vq2tZl28BtgnpUaGq09UxSDZ+tA1PELi4oBwpeVtnkRkKWj9JbbJv3ERY0zGO6+myG0IIa3nndtkWdvsDvnX+pXHDLruOrL0hTmjKhSn+apUdFAUgOP8YmaJYlQ/NiVUt7KeaAP7MO9GCH7cPO1Fv5XNY+FIFHNS1a1alef2OD5Kz6RrSiilW1X1aCD0OS9eAFMZ25C7W0AMC/AwqnMWjqGYaqEMDKUGfrhFBPt0+gIWCQ/ppKNskyp5tWI5Dzhuz4OnA8nO9eHi2oEwxHmLfvEE+rMJkUrNXeRTIHPLzLfdG3wKN7Py+SnaUHZVahgfJZecW2Vzc7hVxvm1XWaqV1cQKKxhtpapmJYSgRYk2gQr4ae49ygY='
  on:
    tags: true
    node: 'stable'
  skip_cleanup: true

addons:
  code_climate:
    repo_token:
      secure: 'Wgi0KrB2IgR+QIhieZSYqSWQ9pGmiMXNJXT/tCeu9SPlb4Che7Tzx/V49Dvgi2zJuEiSTx1O5rL0J1CGxAoGnphRD4GmlhuEOodBFUGKHQjCc4y3uEbiGFpg+1GDnuNmkDcqbKcOXGsGHyq63+uQCN4cPmHHYI7GXHkR7B58fUGAaYYDfXp4sxIQnzxRqSn/hnMdJ5CVgr0uV7os05kGaeei5SFxksfb7x23ZvcaPXKQ7h/kl/bvMz0g2E7zYI+xfJMcS6fOP6blXPEUeBMRgDCuO827TrICMPa5KCT1Qe62nmduaqZ6Y2tNetGgcfyOg+9GzCLrwLVTsaDVeHk8SmUOc6+0hedZIR9N2S4NkwqAqRe4M6sUA8A6PfbvOxY8xHPMrJ/chWqYWm6+ckFvMLAfTK0OtyvEoivp5bmRbQ0o7y6ugZiJvhqSXI6AF37HvWX1CxxXHyma5mwgi+pHzO9nAJ3Br83etLJJ3ATgmx6DiOaYl7W/VOawtM8aP2sgAZuJrV+8Dinu4eeH3v/1nBSqEovy1yszIVSErgfpnh6B+72LQQya28jz2xjeDUOcu4lm+0yiC+0SqgQmFyA6yMLY8oIvHCE12c8Rh4WvL6k1YPng8psHnIl/4azE+qCMQcZV+7cuvGQDKS3eEgGPOz+Z4ZrJ6/gGLQCnt0qyeUA="'