# overrides default:
# https://github.com/brigade/scss-lint/blob/master/config/default.yml
# docs: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

scss_files: '**/src/**/*.scss'

linters:
  Comment:
    enabled: false

  ColorVariable:
    enabled: false

  DisableLinterReason:
    enabled: true

  TrailingZero:
    enabled: true

  VariableForProperty:
    enabled: true
    properties:
      - 'font-family'

  # used by both mixins as variables
  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase
    function_convention: hyphenated_lowercase
    mixin_convention: hyphenated_lowercase
    placeholder_convention: hyphenated_lowercase
    variable_convention: camel_case

  Indentation:
    allow_non_nested_indentation: false
    character: tab
    width: 1

  StringQuotes:
    enabled: true
    style: single_quotes

  ImportPath:
    leading_underscore: false
    filename_extension: false

  LeadingZero:
    enabled: true
    style: exclude_zero

  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  PropertySortOrder:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase

  PropertySpelling:
    enabled: true
    extra_properties:
      - '*zoom'
      - 'will-change'

  FinalNewline:
    enabled: true

  TransitionAll:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true

  PseudoElement:
    enabled: false
